### ISSUE TITLE
Warning fixes and support for more asm at the landing site

### ISSUE THREAD

**Issue by nico** [rentzsch/mach_star#2]
Hi,

I added mach_override to the chromium source today. I made a few changes to its code. [README.chromium](http://src.chromium.org/viewvc/chrome/trunk/src/third_party/mach_override/README.chromium?view=markup) gives an overview of the changes, [chromium.diff](http://src.chromium.org/viewvc/chrome/trunk/src/third_party/mach_override/chromium.diff?view=markup) contains the diff.

You might want to merge these changes (maybe except the removal of mach_override() and the removal of ".globl _atomic_mov64;".

Nico

**Comment by rentzsch** [comment]
Thanks, I merged your patch.
