### ISSUE TITLE
mach_override: some instructions unknown! Need to update mach_override.c

### ISSUE THREAD

**Issue by rtibdewal** [rentzsch/mach_star#25]
Hello there,

I try to override any method, it always fails with trail of messages.

mach_override: some instructions unknown! Need to update mach_override.c
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:227
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:240
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:246
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:260
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:265
_CGContextSetLineWidth Override failed!
mach_override: some instructions unknown! Need to update mach_override.c
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:227
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:240
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:246
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:260
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:265
_DisposeWindow Override failed!
mach_override: some instructions unknown! Need to update mach_override.c
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:227
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:240
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:246
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:260
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:265
_posix_spawn Override failed!
mach_override: some instructions unknown! Need to update mach_override.c
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:227
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:240
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:246
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:260
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:265
 _puts Override failed!

I am mach_inject.h /.c file for injection and mach_override.h/.c for overriding. 
I use sudo with executable in oder to inject. 
Injection appears to be successful with message,

mach_inject failing.. (os/kern) successful
mach inject done? 0

But overriding fails.

I am using 10.6.8 OS X version and XCode 3.2.

Am I doing something wrong?

**Comment by dgivone** [comment]
Why was this issue closed?

**Comment by rtibdewal** [comment]
There were a fix around 3-4 months ago (Nov 02, 2011 and Nov 09, 2011). That has fixed this problem. 
However it can still be reproduced, but only for some cases.  

I will test more and will log different issue for it.
