### ISSUE TITLE
mach_inject on Sandbox Applications

### ISSUE THREAD

**Issue by alexzielenski** [rentzsch/mach_star#3]
Hello, whenever I attempt a mach_inject_bundle on a sandboxed application console outputs, "deny file-read-data path/to/bundle'

Ideas?

**Comment by albertz** [comment]
That is because the sandbox denies the file read to the bundle. You cannot really work around the sandbox.

However, in most cases, the sandbox is setup in a way that it still can read from /System. So try to copy and load your bundle from there.

**Comment by alexzielenski** [comment]
Can anyone confirm this? I tried and it didn't work. Perhaps I am doing it incorrectly...

**Comment by alexzielenski** [comment]
Got it to work, nevermind. Thanks albertz
