### ISSUE TITLE
Bundle Load Error on OS X 10.7 Lion

### ISSUE THREAD

**Issue by louislang** [rentzsch/mach_star#36]
I am currently attempting to inject on OS X 10.7.4, using a bundle I have successfully injected on OS X 10.6.8 (Snow Leopard). The bundle seems to load just fine, in that mach_error_t (from mach_inject_bundle_pid) returns ERR_SUCCESS. However, in my Console.app I see the following line:

```
4:24:00 PM com.my.test_app: mach_ error on bundle load (?/?) (f8000004)
```

I've dumbed my bundle down to a simple +(void) load (with an NSLog), and nothing more to remove as many variables as possible. I've also recompiled the mach_inject_bundle.framework, and rewrote my injector (with more debugging output). 

Is this a known issue?

**Comment by louislang** [comment]
Seems it was looking for a fully qualified path.

**Comment by rentzsch** [comment]
heh, I was just going to chime in your bug was news to me. Thanks for the follow-up.
