### ISSUE TITLE
Wrong vm_protect sizes for i386 architecture

### ISSUE THREAD

**Issue by mkrautz** [rentzsch/mach_star#4]
Hey,

Just a FYI for now...

Just ran into a problem with the Mumble overlay on 10.6.8.

When trying to override CGLFlushDrawable on 10.6.8, I got a segfault.  Turns out that in 10.6.8, OpenGL.framework pages are now marked as write-protected by default.

What happens is that the calls to vm_protect at https://github.com/rentzsch/mach_star/blob/master/mach_override/mach_override.c#L201 uses sizeof(long) as the size of the region to work with.

The problem occurs when calling atomic_mov64, which obviously touches a region greater than sizeof(long).

**Comment by rentzsch** [comment]
I just did this find+replace via Github's text editor. Would be great if you could test it and make sure it's right.

**Comment by mkrautz** [comment]
Probably isn't right, since sizeof(long) == sizeof(void *), right?  Perhaps the most correct fix is simply to replace the sizeof with an 8?

I think an 8 would be just as clear of the intent as sizeof(unsigned long long) and sizeof(uint64) would.

**Comment by rentzsch** [comment]
> Probably isn't right, since sizeof(long) == sizeof(void *)

Yes, sizeof(long) == sizeof(void_) for 32-bit and 64-bit (LP64) systems, so you're right my patch is effectively a no-op. But in my book `sizeof(void_)`captures intent better than`sizeof(long)`or just a hard-coded`8`.

Maybe I'm not understanding something since `sizeof(long)` should actually be OK even on x86-64 (since `sizeof(long) == 8`).

**Comment by mkrautz** [comment]
As I see it, the goal is to move the jumpRelativeInstruction that's constructed in the function into the first 8 bytes of the original (to-be-overridden) function.

**Comment by rentzsch** [comment]
Ah, gotcha it's not just a pointer rewrite it's the jump island. Pull request merged. Thanks!

**Comment by markmentovai** [comment]
I think this should have been sizeof(jumpRelativeInstruction) (== sizeof(uint64_t)) on x86 and x86_64, and sizeof(originalInstruction) (== sizeof(long)) on ppc.

sizeof(branchAbsoluteInstruction) would be even better on ppc, but it’s not yet defined at this point. Both are “long,” and on ppc, instructions are fixed-length anyway, so it’s no big deal.

It appears that none of this works on ppc64 anyway so I won’t bother mentioning anything about that.
