### ISSUE TITLE
Lion i386 compatibility

### ISSUE THREAD

**Issue by markmentovai** [rentzsch/mach_star#7]
Hi, Wolf. I’ve got another change for you courtesy of Google Chrome.

The symptom was that mach_override was causing crashes, but only when we built under Lion. The punchline: data pages are no longer executable by default on Lion when running an executable produced on Lion.

All of the details are available at http://crbug.com/79642#c17 .

mach_override already contains code to mark data pages as executable, but it’s only in use on x86_64. It needs to be enabled for 32-bit x86 too, and a couple of other changes need to be made to ensure reliability.

This change is safe for pre-Lion systems.

http://codereview.chromium.org/7492012 contains our fix for this problem. A direct link to the patch is http://codereview.chromium.org/download/issue7492012_7001_7004.diff . README.chromium has a description of the changes I’m making. Duplicated here:

Enabled makeIslandExecutable for 32-bit i386. Main executables linked and run on Mac OS X 10.7 ("Lion") have non-executable heap pages by default. See http://crbug.com/79642.

Changed the logic surrounding calls to makeIslandExecutable so that mach_override_ptr can return successfully when originalFunctionReentryIsland, an optional argument, is NULL. Failure in makeIslandExecutable will now trigger cleanup of allocated memory.

Changed allocateBranchIsland to use a more appropriate address range per http://developer.apple.com/library/mac/#documentation/Performance/Conceptual/LaunchTime/Articles/Prebinding.html. The range for x86 (32-bit) with kAllocateHigh set is now [0xffc00000, 0xffe00000). In this configuration, the loop is now guaranteed to terminate instead of exceeding its permitted range. Previously, this function would begin looking for a page at 0xfefff000 and would not stop, even after wrapping around to low memory. The URL above states 0xfefff000 is within a range marked "Reserved for use by the pasteboard and other system services. Do not use this address range."

**Comment by markmentovai** [comment]
The safe range is actually [0xffc00000, 0xfffe0000).

**Comment by rentzsch** [comment]
Cool, thanks. I've merged in your changed.
